### ISSUE TITLE
handler.GetTypeDocumentation function throwing error for specific input types. Here the typeId is "UnityEditor.EditorGUI"

### ISSUE THREAD

**Issue by pkodathala-rythmos** [frostebite/UnityApiDocs#7]
The issue here is,
Upon
`<type>`
        `<id>UnityEditor.EditorGUI</id>`
        `<parentId></parentId>`
        `<name>EditorGUI</name>`
        `<kind>Class</kind>`
        `<namespace>UnityEditor</namespace>`
        `<relativeFilePaths>`
            `<path>EditorGUI.cs</path>`
            `<path>EditorGUI.EnumMaskField.deprecated.cs</path>`
            `<path>GUI\AngularDial.cs</path>`
            `<path>GUI\ButtonWithAnimatedIcon.cs</path>`
            `<path>GUI\EditorGUIContents.cs</path>`
            `<path>GUI\GradientField.cs</path>`
            `<path>GUI\HexColorTextField.cs</path>`
            `<path>GUI\InternalEditorGUI.cs</path>`
            `<path>GUI\Knob.cs</path>`
            `<path>GUI\ObjectField.cs</path>`
            `<path>GUI\SliderWithTexture.cs</path>`
            `<path>GUI\TargetChoiceHandler.cs</path>`
            `<path>GUI\TextFieldDropDown.cs</path>`
            `<path>GUI\VUMeter.cs</path>`
        `</relativeFilePaths>`
    `</type>`

When i call
`handler.GetTypeDocumentation(type.Id, type.RelativeFilePaths.ToArray())`

Throwing error:  'allowSceneObjects' is an unexpected token. Expecting whitespace. Line 1327, position 70.

**Comment by adrianoc-unity3d** [comment]
Fixed in branch  *literal_string_quotes*
