### ISSUE TITLE
handler.GetTypeDocumentation function throwing error for specific input types. Here the typeId is "UnityEditor.EditorUserBuildSettings"

### ISSUE THREAD

**Issue by pkodathala-rythmos** [frostebite/UnityApiDocs#8]
The issue here is,
Upon
`<type>`
		`<id>UnityEditor.EditorUserBuildSettings</id>`
		`<parentId></parentId>`
		`<name>EditorUserBuildSettings</name>`
		`<kind>Class</kind>`
		`<namespace>UnityEditor</namespace>`
		`<relativeFilePaths>`
			`<path>EditorUserBuildSettings.bindings.cs</path>`
			`<path>EditorUserBuildSettings.deprecated.cs</path>`
		`</relativeFilePaths>`
	`</type>`

When i call
handler.GetTypeDocumentation(type.Id, type.RelativeFilePaths.ToArray())

Throwing error: 'IL2CPP' is an unexpected token. Expecting whitespace. Line 989, position 129.

**Comment by adrianoc-unity3d** [comment]
Fixed in branch *literal_string_quotes*
